modules:
  # HTTP probe
  http_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      # ip4 needed, if docker isn't setup for ipv6!
      preferred_ip_protocol: ip4
  # HTTPS probe
  https_2xx:
    prober: http
    timeout: 5s
    http:
      method: GET
      fail_if_not_ssl: true
      # ip4 needed, if docker isn't setup for ipv6!
      preferred_ip_protocol: ip4